
create table sensor_monitor_event
(
  sensor_monitor_event_skey  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  create_ts datetime,
  start datetime ,
  stop datetime
);

create table sensor_monitor_event_item
(
    sensor_monitor_event_item_skey  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
     sensor_monitor_event_skey integer,
    recordedDateTime datetime ,
    measurement decimal

);





